### ISSUE TITLE
Question about the API

### ISSUE THREAD

**Issue by DiBaDu** [marburger93/SinusBot-API-PHP-Class#3]
Hello,

how i can use this API ? For Example to include it in the Easy-Wi Webinterface? Can you give me an Example?

German:

Moin, wollte fragen wie man die API Schnittstelle benutzt, so dass man sie beispielsweise im Easy-wi Webinterface einbinden kann

**Comment by marburger93** [comment]
Hallo,

bitte schaue dir die vorhanden Beispiele im Ordner "examples" an. Eine Kompatibilität für Easy-wi müsste erst programmiert werden. 

Bitte beachten Sie aber, dass für diesen Zweck ohnehin eine Lizenz notwendig ist. SinusBot ist nur für den eigenen Gebrauch kostenfrei, andernfalls musst du dich mit dem Autor von SinusBot in Verbindung setzen.

> This software is free for personal use only. If you want to use it commercially, please contact the author.
